import Head from 'next/head'
import { Container , Alert } from 'react-bootstrap'
import 'bootstrap/dist/css/bootstrap.min.css';

export default function Home() {
  return (
    <Container >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

   <Alert className="h1" variant="success">hello</Alert> 
    </Container>
  )
}
