import Head from 'next/head'
import { Container , Button , Alert } from 'react-bootstrap'
import 'bootstrap/dist/css/bootstrap.min.css';
import firebase from "../firebase/initfirebase";
import WriteToCloudFireStore from '../Components/cloud/write.js'
firebase()
export default function Home() {
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      

   <Alert variant="success mt-3">
     <h2 className="display-2">hello</h2> 
    
     <Button href="/auth" variant="outline-dark">auth</Button>
     <WriteToCloudFireStore/>
    </Alert> 
    </Container>
  )
}
